#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

HERE="$(cd "$(dirname "$0")" && pwd)"
TOP_LEVEL="$(cd "$HERE/../" && pwd)"

mkdir -p "$TOP_LEVEL/.build"
go -C "$TOP_LEVEL" build -o "$TOP_LEVEL/.build/thing" ./cmd/thing
